apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-import
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: kibana-data
        configMap:
            name: kibana-data
            defaultMode: 0777
      containers:
      - name: kibana-import
        image: centos/centos7
        imagePullPolicy: IfNotPresent
        env:
        - name: KIBANA_URL
          value: "{{ .Values.kibana.serviceName }}"
        - name: KIBANA_PORT
          value: "{{ .Values.kibana.port }}"
        command: ["/bin/sh","/opt/kibana/curl-script.sh"]
        volumeMounts:
        - name: kibana-data
          mountPath: /kibana/