apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fid.fullname" . }}
  labels:
    {{- include "fid.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ template "fid.fullname" . }}
  selector:
    matchLabels:
    {{- include "fid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "fid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
  {{- if .Values.zk.external }}
      - name: check-zk
        image: alpine:latest
        imagePullPolicy: IfNotPresent
#        command: ['sh', '-c', 'apk add -q --no-cache curl && until $(curl --connect-timeout 2 --output /dev/null --silent --fail {{ .Values.zk.ruok }});  do echo waiting for zookeeper -- {{ .Values.zk.ruok }}; sleep 10; done; echo connection to zookeeper ok']
#        command: ['sh', '-c', 'until $(echo "ruok" | timeout 2 nc -w 2 {{ (split ":" .Values.zk.connectionString)._0 }} {{ (split ":" .Values.zk.connectionString)._1 }} | grep -v imok);  do echo waiting for zookeeper -- {{ .Values.zk.connectionString }}; sleep 10; done; echo connection to zookeeper ok']
        command: ['sh', '-c', 'until nc -w 2 -z $0 $1; do echo Waiting for zookeeper -- $0:$1;sleep 2; done; echo Connection to zookeeper ok -- $0:$1', '{{ (split ":" .Values.zk.connectionString)._0 }}', '{{ (split ":" .Values.zk.connectionString)._1 }}']
  {{- end }}
      - name: sysctl
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "sysctl -w vm.max_map_count=262144 && set -e && ulimit -n 65536"]
        securityContext:
          privileged: true
  {{- if hasKey .Values.fid.migration "url" }}
  {{- if .Values.fid.migration.url }}
      - name: migration
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -ex
            # Download the curl package
            apk add -q --no-cache curl
            # Download the migrations file
            curl -sSo /migrations/export.zip {{ .Values.fid.migration.url }}
            
            echo 'Migration file copied to /migrations/export.zip' && ls -ltr /migrations
  {{- if hasKey .Values.fid.migration "script" }}
  {{- if .Values.fid.migration.script }}
            # Download the script
            curl -sSo /opt/radiantone/scripts/test.sh {{ .Values.fid.migration.script }}
            # make it executable
            chmod +x /opt/radiantone/scripts/test.sh            
            echo 'Post migration script copied to /opt/radiantone/scripts/test.sh' && ls -ltr /opt/radiantone/scripts
  {{- end }}
  {{- end }}            
        volumeMounts:
        - name: migrations
          mountPath: /migrations
  {{- if hasKey .Values.fid.migration "script" }}
  {{- if .Values.fid.migration.script }}
        - name: scripts
          mountPath: /opt/radiantone/scripts
  {{- end }}
  {{- end }}            

  {{- end }}
  {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the myfid postStart handler > /opt/radiantone/vds/lifecycle.txt; unset FID_PASSWORD ZK_PASSWORD LICENSE;"]
          preStop:
            exec:
{{- if .Values.fid.detach }}
              command: ["/opt/radiantone/vds/bin/advanced/cluster.sh", "detach"]
{{- else }}
              command: ["/opt/radiantone/vds/bin/stopVDSServer.sh"]
{{- end }}
        ports:
        - containerPort: 2181
          name: zk-client
        - containerPort: 7070
          name: cp-http
        - containerPort: 7171
          name: cp-https
        - containerPort: 9100
          name: admin-http
        - containerPort: 9101
          name: admin-https
        - containerPort: 2389
          name: ldap
        - containerPort: 2636
          name: ldaps
        - containerPort: 8089
          name: http
        - containerPort: 8090
          name: https
        readinessProbe:
          tcpSocket:
            port: 2389
          initialDelaySeconds: {{ .Values.metrics.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.metrics.readinessProbe.timeoutSeconds }}
          periodSeconds: 30
          failureThreshold: 5
          successThreshold: 1
        livenessProbe:
          exec:
            command: [ "/opt/radiantone/check", "run", "-type", "liveness" ]
          initialDelaySeconds: {{ .Values.metrics.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.metrics.livenessProbe.timeoutSeconds }}
          periodSeconds: 30
          failureThreshold: 5
          successThreshold: 1
        envFrom:
        - configMapRef:
            name: {{ template "fid.fullname" . }}
        env:
{{- if .Values.fid.rootUser }}
        - name: FID_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: rootcreds-{{ template "fid.fullname" . }}
              key: fid-root-username
{{- end }}
{{- if .Values.fid.rootPassword }}
        - name: FID_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rootcreds-{{ template "fid.fullname" . }}
              key: fid-root-password
{{- end }}
{{- if .Values.zk.username }}
        - name: ZK_USER
          valueFrom:
            secretKeyRef:
              name: rootcreds-{{ template "fid.fullname" . }}
              key: zk-username
{{- end }}
{{- if .Values.zk.password }}
        - name: ZK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rootcreds-{{ template "fid.fullname" . }}
              key: zk-password
{{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: r1-pvc
          mountPath: /opt/radiantone/vds
        - name: migrations
          mountPath: /migrations
        - name: scripts
          mountPath: /opt/radiantone/scripts
{{- if .Values.fid.readonly }}
        command: ["/bin/sh", "-c", "export CLUSTER=join;./run.sh fg"]
{{- else }}
        command: ["/bin/sh", "-c", "if [ $HOSTNAME != {{ template "fid.fullname" . }}-0 ]; then export CLUSTER=join; fi;./run.sh fg"]
        command: ["/bin/sh", "-c"]
        args: 
          - |
            set -ex
            if [ $HOSTNAME != {{ template "fid.fullname" . }}-0 ]; then 
              export CLUSTER=join; 
            fi;
            ./run.sh
            export FID_PASSWORD=null
            export ZK_PASSWORD=null
            export LICENSE=null
            tail -f /dev/null
{{- end }}
{{- if .Values.metrics.enabled }}
      - name: {{ .Chart.Name }}-exporter
        image: {{ .Values.metrics.image }}:{{ .Values.metrics.imageTag }}
        ports:
        - containerPort: 9095
          name: exporter
        env:
        - name: PUSH_MODE
          value: {{ .Values.metrics.pushMode | quote }}
        - name: PUSHGATEWAY_URI
          value: {{ .Values.metrics.pushGateway | quote }}
        - name: LDAP_URI
          value: "ldap://localhost:2389"
{{- if .Values.fid.rootUser }}
        - name: BIND_DN
          valueFrom:
            secretKeyRef:
              name: rootcreds-{{ template "fid.fullname" . }}
              key: fid-root-username
{{- end }}
{{- if .Values.fid.rootPassword }}
        - name: BIND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rootcreds-{{ template "fid.fullname" . }}
              key: fid-root-password
{{- end }}

{{- end }}
              
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: scripts
        emptyDir: {}
      - name: migrations
        emptyDir: {}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: r1-pvc
      annotations:
      {{- range $key, $value := .Values.persistence.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      labels:
        {{- include "fid.labels" . | nindent 8 }}
    spec:
      accessModes:
      {{- range .Values.persistence.accessModes }}
      - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
{{- else }}
      - name: r1-pvc
        emptyDir: {}
{{- end }}
